Helium-Health/helium-kudos-server

.github/workflows/dev.yaml, .gitignore, migrate-mongo-config.js, migrations/20250304233627-duplicate-email.js, package-lock.json, package.json, scripts/sync-db.js, src/auth/auth.service.ts, src/users/users.service.ts
Reverts Helium-Health/helium-kudos-server#301
=> Revert "Revert "Dev""

src/recognition/recognition.service.ts
Percentage Increase or Decrease for Totol coin and recognition post metrics.
=> Kudos 40 Backend

src/groups/groups.module.ts, src/groups/groups.service.ts, src/order/order.controller.ts, src/recognition/recognition.controller.ts, src/users/dto/User.dto.ts, src/users/schema/User.schema.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
Added a inivite user functionality to add users.
It replaces the flow by which users sign up, the invite verify if user exist on slack before storing the user data.
=> feat: KUDOS-137 Invite User

src/leaderboard/leaderboard.controller.ts, src/leaderboard/leaderboard.service.ts, src/order/order.controller.ts, src/recognition/recognition.service.ts
Added month filter to Post Metrics
Remove redundate (ActiveUserGuard) in post order endpoint.
https://heliumhealth.atlassian.net/browse/KUDOS-140?atlOrigin=eyJpIjoiNzZmMzVlZDQwNzA2NDVkNWE0MWIwNmI5MTg5YjIwZDIiLCJwIjoiaiJ9
https://github.com/user-attachments/assets/b25f50a3-7891-4dbb-a61f-503141d98f7f
=> feat: KUDOS-140: Add month filter to Post Metrics

src/users/users.controller.ts, src/users/users.service.ts
=> feat: KUDOS-141: Resend Invite

src/groups/groups.controller.ts, src/groups/groups.service.ts
=> fix: KUDOS-142: Support Get All Groups

src/milestone/milestone.service.ts, src/users/users.service.ts
=> KUDOS:145 :Disable Celebrations for Deactivated users

src/users/dto/User.dto.ts, src/users/users.controller.ts, src/users/users.service.ts
=> feat: KUDOS-144 Allow Admin Update User Data

src/leaderboard/leaderboard.controller.ts, src/leaderboard/leaderboard.service.ts, src/recognition/recognition.service.ts
=> Add Date Range for Post Metrics

src/leaderboard/leaderboard.controller.ts, src/leaderboard/leaderboard.service.ts, src/recognition/recognition.service.ts, src/transaction/transaction.service.ts, src/users/users.service.ts
=> fix: Invite User

src/leaderboard/leaderboard.controller.ts, src/leaderboard/leaderboard.service.ts, src/wallet/wallet.service.ts
Added date filter to Coin Use Metric Analytics
=> fix: add filter range

src/leaderboard/leaderboard.controller.ts, src/leaderboard/leaderboard.service.ts, src/users/users.service.ts, src/wallet/wallet.service.ts
=> Dev to Staging

src/auth/auth.service.ts, src/users/users.service.ts
This PR fix the internal server error which occur due to Invted User missing wallet account.
https://github.com/user-attachments/assets/0e1e01da-2dc8-469b-b660-7c6f6849549b
=> Invite user wallet fix

src/users/users.service.ts
=> Remove Redundant Code.

src/comment/comment.controller.ts, src/comment/comment.service.ts, src/comment/dto/CreateComment.dto.ts
=> feat: Comment: Edit, Delete, Paginate

src/recognition/recognition.service.ts, src/recognition/schema/Recognition.schema.ts, src/users/dto/UpdateFromSheet.dto.ts, src/users/user-sync.service.ts, src/users/users.service.ts
=> Enhance Recognition Creation (Include Department)

src/recognition/recognition.service.ts
=> Fix: Analytics, exclude auto recognitions

src/users/schema/User.schema.ts, src/users/users.controller.ts, src/users/users.service.ts
=> feat: Show All user including signed in users

src/comment/comment.service.ts, src/comment/dto/CreateComment.dto.ts, src/comment/schema/comment.schema.ts, src/recognition/dto/CreateRecognition.dto.ts, src/recognition/recognition.service.ts, src/recognition/schema/Recognition.schema.ts
=> KUDOS-148: Refactor Recognition and Comment Media Handling

src/comment/comment.service.ts, src/comment/schema/comment.schema.ts
=> add edited props

src/recognition/schema/Recognition.schema.ts
=> fix: fix issue with department based recognition

src/users/users.service.ts
=> feat(milestone): calculate years of service

src/users/user-sync.service.ts
=> fix: list all skipped users

src/product/product.service.ts, src/users/user-sync.service.ts
=> Main <- dev 
